version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.6.10
    hostname: rabbit
    volumes:
      - .tmp/rabbit:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretCookie"
    ports:
      - 5672:5672

  rabbitmq-management:
    image: rabbitmq:3.6.10-management
    hostname: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretCookie"
    volumes:
      - .tmp/rabbit:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    depends_on:
      - rabbitmq
    ports:
      - 15672:15672