version: "3"

services:

  swaggerui:
    image: swaggerapi/swagger-ui:v3.0.5
    ports:
      - 9999:8080

  rabbitmq:
    image: rabbitmq:3.6.10-management
    hostname: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: secretCookie
    volumes:
      - .tmp/rabbit:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    ports:
      - 5672:5672
      - 15672:15672

  calendaring-db:
    image: couchdb:1.6.1
    environment:
      COUCHDB_USER: test
      COUCHDB_PASSWORD: test
    volumes:
      - ./scherule-calendaring/.tmp/db:/usr/local/var/lib/couchdb
    ports:
      - 5984:5984